# Generated by Django 4.2 on 2023-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservaModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_do_pet",
                    models.CharField(max_length=50, verbose_name="Nome do pet"),
                ),
                ("telefone", models.CharField(max_length=50, verbose_name="Telefone")),
                ("data_da_reserva", models.DateField(verbose_name="Data de reserva")),
                ("observacao", models.TextField(verbose_name="Observação")),
            ],
        ),
    ]
