# Generated by Django 4.2 on 2023-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basico", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservamodels",
            name="observacao",
        ),
        migrations.AddField(
            model_name="reservamodels",
            name="observacoes",
            field=models.TextField(default="nulo", verbose_name="Observações"),
        ),
    ]
